baseURL = "http://mycompany.com/"
languageCode = "en-us"
title = "My Company"
summaryLength = 20
disqusShortname = ""
googleAnalytics = ""
Paginate = 10
PaginatePath = "/"
enableRobotsTXT = true
theme = "justice"

[permalinks]
  posts = ":section/:year/:month/:day/:title/"

# Generic parameters

[params]
  appendSiteTitle = true # Append site title to title tag on every page. Default false
  favicon = 'img/favicon.ico'
  subtitle = "The development site for now"

[params.meta]
  backgroundImagePath = "img/garden.jpg"
  description = "Building the site the way I want it."
  keywords = "web site,justice theme"


  readmore = "true"
  post_navigation = true
  postSections = ["blog"]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
        
[params.navbar]
  #backgroundColor = 

[params._selectData]
  call_to_actions = ["Contact", "Blog", "Map"]
  #social_icons = ["Facebook", "Instagram", "LinkedIn", "Pinterest", "Tumblr", "Twitter", "YouTube", "RSS"]

[params._options.type]
  hidden = true

[params._comments]
  large_header = "Toggles the size of the top banner."
  show_in_navigation = "Toggles a link in the top banner."
  author_staff_member = "The staff member writing this post."
  call_to_action = "Type of request shown at the bottom of this page."
  background_image_path = "Image shown in the top banner, blank for the default."
  testimonials = "Update"
  map = "Update the map location and display settings."
  latitude = "Coordinates for the center marker on the map."
  longitude = "Coordinates for the center marker on the map."
  zoom = "The zoom level for the map."
  phone_extension = "The digits after dialing the company phone."
  credentials = "Shown as subtext on staff member summaries."
  contact_email_address = "Address for the contact form to send to."
  new_window = "Whether the link opens a new browser tab/window."

# Menu section

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 100

  [[menu.main]]
    identifier = "kudos"
    name = "What Clients Say"
    url = "/testimonials/"
    weight = 200

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 300

  [[menu.main]]
    identifier = "expertise"
    name = "Expertise"
    url = "/about/expertise/"
    parent = "about"
    weight = 301

  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/about/experience/"
    parent = "about"
    weight = 302
   
  [[menu.main]]
    identifier = "education"
    name = "Education"
    url = "/about/education/"
    parent = "about"
    weight = 303

  [[menu.main]]
    identifier = "library"
    name = "Library"
    url = "/library/"
    weight = 400

  [[menu.main]]
    identifier = "sub1"
    name = "Subject 1"
    url = "/library/subject-1/"
    parent = "library"
    weight = 401

  [[menu.main]]
    identifier = "sub2"
    name = "Subject 2"
    url = "/library/subject-2/"
    parent = "library"
    weight = 402

  [[menu.main]]
    identifer = "sub3"
    name = "Subject 3"
    url = "/library/subject-3/"
    parent = "library"
    weight = 403

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 500

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 600
