baseURL = "http://mycompany.com/"
languageCode = "en-us"
title = "My Company"
summaryLength = 20
disqusShortname = ""
googleAnalytics = ""
Paginate = 10
PaginatePath = "/"
enableRobotsTXT = true
theme = "justice"

[permalinks]
  posts = ":section/:year/:month/:day/:title/"

# Generic parameters

[params]
  appendSiteTitle = true # Append site title to title tag on every page. Default false
  favicon = './static/img/favicon.ico'
  subtitle = "The development site for now"

[params.meta]
  backgroundImagePath = "./static/img/garden.jpg"
  description = "Building the site the way I want it."
  keywords = "web site,justice theme"
  
  readmore = "true"
  post_navigation = true
  postSections = ["blog"]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
        
[params.navbar]
  #backgroundColor = 

[params._selectData]
  call_to_actions = ["Contact", "Blog", "Map"]
  #social_icons = ["Facebook", "Instagram", "LinkedIn", "Pinterest", "Tumblr", "Twitter", "YouTube", "RSS"]

[params._options.type]
  hidden = true

[params._comments]
  large_header = "true"
  show_in_navigation = "Toggles a link in the top banner."
  author_staff_member = "Me"
  call_to_action = "Type of request shown at the bottom of this page."
  background_image_path = "./static/img/favicon.ico"
  testimonials = "Update"
  map = "Update the map location and display settings."
  latitude = "Coordinates for the center marker on the map."
  longitude = "Coordinates for the center marker on the map."
  zoom = "The zoom level for the map."
  phone_extension = "The digits after dialing the company phone."
  credentials = "Ph.D."
  contact_email_address = "info@mycompany.com"
  new_window = "Whether the link opens a new browser tab/window."

